spring:
  profiles:
    include: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true