name: DND Share Diary

on:
  push:
    branches: [ "main" ]

env:
  S3_BUCKET_NAME: dnd-diary-deploy
  PROJECT_NAME: dnd-8th-4-backend

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup jdk-17
      uses: actions/setup-java@main
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: make application-dev.yml
      run: |
        # create application-dev.yml
        cd ./src/main/resources

        # application-dev.yml 파일 생성
        touch ./application-dev.yml

        # GitHub-Actions 에서 설정한 값을 application-dev.yml 파일에 쓰기
        echo "${{ secrets.PROPERTIES_DEV }}" >> ./application-dev.yml
        echo "${{ secrets.PROPERTIES }}" >> ./application.yml
      shell: bash

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Make zip file
      run: zip -r ./$GITHUB_SHA.zip .
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload to S3
      run: |
        aws s3 cp \
        --region ap-northeast-2 \
        ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

    - name: Code Deploy
      run: |
        aws deploy create-deployment \
        --application-name DND-dirary-CodeDeploy \
        --deployment-config-name CodeDeployDefault.AllAtOnce \
        --deployment-group-name deploy \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
